# Generated by Django 5.0.1 on 2024-01-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productimage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productoption',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
